export const SET_USERINFO='SET_USERINFO';
export const SET_NAVBARS='SET_NAVBARS';
export const SET_SHORTCUT='SET_SHORTCUT';
export const SET_WORKTOTAL='SET_WORKTOTAL';
export const SET_MSGTOTAL='SET_MSGTOTAL';
